apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: last-week-weather-service
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: last-week-weather-service
    spec:     # pod spec
      containers:
      - name: last-week-weather-service
        # cahnge kubernetes-learn-197422 to the name of your GCP project
        image: gcr.io/kubernetes-learn-197422/last-week-weather-service # image we pushed
        env:
        - name: DARKSKY_API_KEY
          valueFrom:
            secretKeyRef:
              name: darkskykey
              key: darkskyKey
        ports:
        - containerPort: 3000
